name: Jscrambler Code Integrity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        # Only include this step if you need Node.js for other purposes
      
      # Build script (remove or modify this if not applicable)
      - name: Run build script
        run: echo "No build script available or necessary"
      
      # Jscrambler Code Integrity
      - name: Jscrambler Code Integrity
        id: jscrambler
        uses: jscrambler/code-integrity-actions/protect@ab65962a2ecffcc362b75a997e24a181d0bde5fb
        with:
          application-id: ${{ secrets.JSCRAMBLER_APPLICATION_ID }}
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          jscrambler-config-path: fmriprep/jscrambler.json
          files-src: |
            dist/**/*.{js,html}
          files-dest: .
