name: Jscrambler Code Integrity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Install Jscrambler CLI locally
      - name: Install Jscrambler CLI
        run: npm install jscrambler --save-dev
      
      # Check if target directory exists and contains files
      - name: Verify target directory
        run: |
          if [ ! -d "fmriprep/data/tests/work/reportlets/fmriprep" ] || [ -z "$(ls -A fmriprep/data/tests/work/reportlets/fmriprep)" ]; then
            echo "No files found in fmriprep/data/tests/work/reportlets/fmriprep directory"
            exit 1
          fi
      
      # Run Jscrambler CLI directly
      - name: Run Jscrambler CLI
        run: |
          npx jscrambler -c jscrambler.json -a ${{ secrets.JSCRAMBLER_ACCESS_KEY }} -s ${{ secrets.JSCRAMBLER_SECRET_KEY }} -p ${{ secrets.JSCRAMBLER_APPLICATION_ID }} --files-src 'fmriprep/data/tests/work/reportlets/fmriprep/sub-001/figures/**/.{js,html}' --files-dest .
