name: Jscrambler Code Integrity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Install dependencies and generate package-lock.json
      - name: Install dependencies
        run: npm install
      
      # Check if package-lock.json exists
      - name: Check if package-lock.json exists
        id: check-lockfile
        run: echo "exists=$(if [ -f package-lock.json ]; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_ENV
      
      # Use npm ci for clean install if package-lock.json exists
      - name: Clean install dependencies
        if: env.exists == 'true'
        run: npm ci
      
      # Run build script
      - run: npm run build
      
      # Jscrambler Code Integrity
      - name: Jscrambler Code Integrity
        id: jscrambler
        uses: jscrambler/code-integrity-actions/protect@ab65962a2ecffcc362b75a997e24a181d0bde5fb
        with:
          application-id: ${{ secrets.JSCRAMBLER_APPLICATION_ID }}
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          jscrambler-config-path: jscrambler.json
          files-src: |
            dist/**/*.{js,html}
          files-dest: .
