name: Jscrambler Code Integrity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Install Jscrambler CLI
      - name: Install Jscrambler CLI
        run: npm install -g jscrambler@latest
      

      # Check if target directory exists and contains files
      - name: Verify target directory
        run: |
          if [ ! -d "fmriprep/data/tests/work/reportlets/fmriprep" ] || [ -z "$(ls -A fmriprep/data/tests/work/reportlets/fmriprep)" ]; then
            echo "No files found in fmriprep/data/tests/work/reportlets/fmriprep directory"
            exit 1
          fi
      
      # Jscrambler Code Integrity
      - name: Jscrambler Code Integrity
        id: jscrambler
        uses: jscrambler/code-integrity-actions/protect@ab65962a2ecffcc362b75a997e24a181d0bde5fb
        with:
          application-id: ${{ secrets.JSCRAMBLER_APPLICATION_ID }}
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          jscrambler-config-path: jscrambler.json  # Ensure this path is correct
          files-src: |
            fmriprep/data/tests/work/reportlets/fmriprep/**/*.{js,html}
          files-dest: .
          source-maps-source-content: true
